export {
  getAllEstados,
  getAllMunicipios,
  getEstados,
  getMunicipios,
  getMunicipioPorCodigo,
  lookupMunicipioPorCodigo,
  computeCmunFgCheckDigit,
  parseCmunFg,
  toCmunFg,
  IBGE_DATA_VERSION,
  IBGE_OFFICIAL_DOCS_URL,
  IBGE_ESTADOS_URL,
  IBGE_MUNICIPIOS_URL,
  IBGE_MUNICIPIO_CODIGOS_URL,
  NFE_MOC_ANEXO_I_URL,
  CMUNFG_GOLDEN_BASE_SAO_PAULO,
  CMUNFG_GOLDEN_EXCEPTION_BOM_PRINCIPIO,
  CMUNFG_GOLDEN_SAO_PAULO,
  IBGE_GOLDEN_MUNICIPIO_SP,
  IBGE_GOLDEN_MUNICIPIO_SORRISO,
  IBGE_GOLDEN_MUNICIPIO_BRASILIA,
  IBGE_GOLDEN_ESTADO_SP,
  IBGE_UF_SIGLAS,
} from './ibge/index.js';
export type {
  CmunFgParseFailure,
  CmunFgParseFailureReason,
  CmunFgParseResult,
  CmunFgParseSuccess,
  Estado,
  IbgeDataVersion,
  IbgeRegiao,
  Municipio,
} from './ibge/types.js';
